---
title: "Data_Import"
author: "Briana Lettsome"
date: "September 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Import FAS csv files

Import my 1st csv.

```{r}
litters_dataII = read_csv(file = "./data/FAS_litters.csv")
litters_dataII = janitor:: clean_names(litters_dataII)

litters_dataII
```

## Lecture Assessment 1 - Data Wrangling Lecture

Importing data files

Import pups dataset

Relative and Absolute Paths
```{r}
pups_dataII = read_csv(file = "./data/FAS_pups.csv")

pups_dataII


```


## Look at data

Look at litters data

```{r}

litters_dataII

head(litters_dataII)
tail(litters_dataII)

skimr::skim(litters_dataII)
```


Skip some rows, omit variable names.

```{r}
 = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
```

Look at pups!

```{r}
pups_dataII = janitor::clean_names(pups_dataII)
pups_dataII
skimr::skim(pups_dataII)
```


## Other formats

Read in mlb data

```{r}
library(tidyverse)

mlb_data = readxl::read_excel(path = "./data/mlb11.xlsx")

mlb_data

 = read_excel(path = "./data/mlb11.xlsx"," range = "A1:E17")

mlb_subset
```
having a hard time doing absolute names and this subset part

Read in pulse dataset
